### ISSUE TITLE
Error while pairing the new device

### ISSUE THREAD

**Issue by EffeF** [louis49/homebridge-plugin-androidtv#14]
When I try to pair a new device (Nvidia SHIELD TV) the code only appears for a fraction of a second, preventing me from entering it on the configuration page.

And in the logs I have the following errors:
```console
[2/7/2022, 2:29:39 AM] Error: EACCES: permission denied, open 'androidtv-config.json'
    at Object.openSync (node:fs:585:3)
    at Object.writeFileSync (node:fs:2153:35)
    at DeviceManager.save (/homebridge/node_modules/homebridge-androidtv/dist/homebridge/DeviceManager.js:78:17)
    at /homebridge/node_modules/homebridge-androidtv/dist/homebridge/admin/api.js:55:21
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/homebridge/node_modules/homebridge-androidtv/dist/homebridge/admin/api.js:18:103)
    at _next (/homebridge/node_modules/homebridge-androidtv/dist/homebridge/admin/api.js:20:194)
    at /homebridge/node_modules/homebridge-androidtv/dist/homebridge/admin/api.js:20:364
    at new Promise (<anonymous>)
    at /homebridge/node_modules/homebridge-androidtv/dist/homebridge/admin/api.js:20:97
[2/7/2022, 2:29:39 AM] Got SIGTERM, shutting down Homebridge...
Start Pairing Connect
[2/7/2022, 2:29:44 AM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[2/7/2022, 2:29:49 AM] [HB Supervisor] Restarting Homebridge...
```

Homebridge: v1.4.0
Homebridge Androidtv: v2.0.16
OS: Ubuntu Bionic Beaver (18.04.6 LTS)
Docker: yes

**Comment by 7k3ela** [comment]
Hi

I have a same issue with my Sony Bravia Android TV and Prism+ Android TV (Singapore).

Homebridge: v.1.4.0
Homebridge-androidtv: V2.0.16
Homebridge running on Docker within Synology NAS DS916+, DSM7

**Comment by louis49** [comment]
The pull request is now available in main branch

**Comment by 7k3ela** [comment]
Just install this again into my Homebridge environment.
Able to register my Android TVs without any error.
Thank you~

**Comment by EffeF** [comment]
It works now, thanks
