### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by galeoner** [louis49/homebridge-plugin-androidtv#6]
Hey! I really liked your plugin and I am actively using it. I have a suggestion for improvement.
1. Make the use of channels optional
2. Make the use of applications optional
3. Make a call to applications in the form "com.myapp.myapp"

Ready to sweeten these changes with generosity (donate)
(translated with google, my English leaves much to be desired)

**Comment by louis49** [comment]
Hey!
Thank you for loving my plugin !
For channels and applications optional : can’t you remove all of them and then have no one in HomeKit ? 
For application code I can’t do that because of Google limitation : I can’t send an app code, I need to send a deep link. I you want I can seak a deep link for any app : I just need the apk - feel free to send me a link to it - I will update the doc for this app

**Comment by galeoner** [comment]
ATV home launcher (for easy switch)
my apps:
1. Televizo
https://play.google.com/store/apps/details?id=com.ottplay.ottplay
2. Kinopub (not in PlayMarket)
https://kpdl.cc/k.apk

**Comment by louis49** [comment]
I will look on it tomorrow morning

**Comment by galeoner** [comment]
About channels... for test I'm remove section with channels from main homebridge json and then restart server - errors on start. work 1-2 seconds, then error.

[05/01/2022, 13:46:30] TypeError: this.config.channels is not iterable
    at AndroidTV.discover (/usr/local/lib/node_modules/homebridge-androidtv/dist/homebridge/platform.js:163:37)
    at DeviceManager.emit (events.js:400:28)
    at AndroidRemote.<anonymous> (/usr/local/lib/node_modules/homebridge-androidtv/dist/homebridge/DeviceManager.js:152:17)
    at AndroidRemote.emit (events.js:400:28)
    at RemoteManager.<anonymous> (/usr/local/lib/node_modules/homebridge-androidtv/node_modules/androidtv-remote/dist/index.js:68:51)
    at RemoteManager.emit (events.js:400:28)
    at TLSSocket.<anonymous> (/usr/local/lib/node_modules/homebridge-androidtv/node_modules/androidtv-remote/dist/remote/RemoteManager.js:81:21)
    at TLSSocket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)

**Comment by louis49** [comment]
Ok, there is a bug, I never tested this kind of configuration.
I will fix it tomorrow morning too

**Comment by louis49** [comment]
Bug fixed in [V2.0.15](https://www.npmjs.com/package/homebridge-androidtv/v/2.0.15)

**Comment by louis49** [comment]
For ottplay, you can try: "www.ottplay.com"
For kinopub, you can try: "app/browse/.*" => it seems not very compliant, developper let simple "app" value

**Comment by galeoner** [comment]
unfortunately the links don't work.
the error with deleting channels and applications is gone.

**Comment by louis49** [comment]
I will try by installing them on my AndroidTV

**Comment by louis49** [comment]
These application are not compliant with the deep link protocole, maybe a new version of these apps will fix it
